/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempSenseRouteImport } from './routes/temp-sense'
import { Route as SkinSenseRouteImport } from './routes/skin-sense'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PressureSenseRouteImport } from './routes/pressure-sense'
import { Route as MotionSenseRouteImport } from './routes/motion-sense'
import { Route as MapRouteImport } from './routes/map'
import { Route as LightSenseRouteImport } from './routes/light-sense'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as BreedsRouteImport } from './routes/breeds'
import { Route as BarkSenseRouteImport } from './routes/bark-sense'
import { Route as AvatarSetupRouteImport } from './routes/avatar-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingOwnerInfoRouteImport } from './routes/onboarding.owner-info'
import { Route as OnboardingOwnerRouteImport } from './routes/onboarding.owner'
import { Route as OnboardingDogRouteImport } from './routes/onboarding.dog'
import { Route as OnboardingDetailsRouteImport } from './routes/onboarding.details'
import { Route as OnboardingAvatarRouteImport } from './routes/onboarding.avatar'

const TempSenseRoute = TempSenseRouteImport.update({
  id: '/temp-sense',
  path: '/temp-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinSenseRoute = SkinSenseRouteImport.update({
  id: '/skin-sense',
  path: '/skin-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureSenseRoute = PressureSenseRouteImport.update({
  id: '/pressure-sense',
  path: '/pressure-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionSenseRoute = MotionSenseRouteImport.update({
  id: '/motion-sense',
  path: '/motion-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LightSenseRoute = LightSenseRouteImport.update({
  id: '/light-sense',
  path: '/light-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedsRoute = BreedsRouteImport.update({
  id: '/breeds',
  path: '/breeds',
  getParentRoute: () => rootRouteImport,
} as any)
const BarkSenseRoute = BarkSenseRouteImport.update({
  id: '/bark-sense',
  path: '/bark-sense',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarSetupRoute = AvatarSetupRouteImport.update({
  id: '/avatar-setup',
  path: '/avatar-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOwnerInfoRoute = OnboardingOwnerInfoRouteImport.update({
  id: '/onboarding/owner-info',
  path: '/onboarding/owner-info',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOwnerRoute = OnboardingOwnerRouteImport.update({
  id: '/onboarding/owner',
  path: '/onboarding/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDogRoute = OnboardingDogRouteImport.update({
  id: '/onboarding/dog',
  path: '/onboarding/dog',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDetailsRoute = OnboardingDetailsRouteImport.update({
  id: '/onboarding/details',
  path: '/onboarding/details',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAvatarRoute = OnboardingAvatarRouteImport.update({
  id: '/onboarding/avatar',
  path: '/onboarding/avatar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/avatar-setup': typeof AvatarSetupRoute
  '/bark-sense': typeof BarkSenseRoute
  '/breeds': typeof BreedsRoute
  '/clinics': typeof ClinicsRoute
  '/community': typeof CommunityRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/light-sense': typeof LightSenseRoute
  '/map': typeof MapRoute
  '/motion-sense': typeof MotionSenseRoute
  '/pressure-sense': typeof PressureSenseRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/skin-sense': typeof SkinSenseRoute
  '/temp-sense': typeof TempSenseRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/details': typeof OnboardingDetailsRoute
  '/onboarding/dog': typeof OnboardingDogRoute
  '/onboarding/owner': typeof OnboardingOwnerRoute
  '/onboarding/owner-info': typeof OnboardingOwnerInfoRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/avatar-setup': typeof AvatarSetupRoute
  '/bark-sense': typeof BarkSenseRoute
  '/breeds': typeof BreedsRoute
  '/clinics': typeof ClinicsRoute
  '/community': typeof CommunityRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/light-sense': typeof LightSenseRoute
  '/map': typeof MapRoute
  '/motion-sense': typeof MotionSenseRoute
  '/pressure-sense': typeof PressureSenseRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/skin-sense': typeof SkinSenseRoute
  '/temp-sense': typeof TempSenseRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/details': typeof OnboardingDetailsRoute
  '/onboarding/dog': typeof OnboardingDogRoute
  '/onboarding/owner': typeof OnboardingOwnerRoute
  '/onboarding/owner-info': typeof OnboardingOwnerInfoRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/avatar-setup': typeof AvatarSetupRoute
  '/bark-sense': typeof BarkSenseRoute
  '/breeds': typeof BreedsRoute
  '/clinics': typeof ClinicsRoute
  '/community': typeof CommunityRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/light-sense': typeof LightSenseRoute
  '/map': typeof MapRoute
  '/motion-sense': typeof MotionSenseRoute
  '/pressure-sense': typeof PressureSenseRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/skin-sense': typeof SkinSenseRoute
  '/temp-sense': typeof TempSenseRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/details': typeof OnboardingDetailsRoute
  '/onboarding/dog': typeof OnboardingDogRoute
  '/onboarding/owner': typeof OnboardingOwnerRoute
  '/onboarding/owner-info': typeof OnboardingOwnerInfoRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/avatar-setup'
    | '/bark-sense'
    | '/breeds'
    | '/clinics'
    | '/community'
    | '/home'
    | '/language'
    | '/light-sense'
    | '/map'
    | '/motion-sense'
    | '/pressure-sense'
    | '/report'
    | '/settings'
    | '/skin-sense'
    | '/temp-sense'
    | '/onboarding/avatar'
    | '/onboarding/details'
    | '/onboarding/dog'
    | '/onboarding/owner'
    | '/onboarding/owner-info'
    | '/onboarding/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/avatar-setup'
    | '/bark-sense'
    | '/breeds'
    | '/clinics'
    | '/community'
    | '/home'
    | '/language'
    | '/light-sense'
    | '/map'
    | '/motion-sense'
    | '/pressure-sense'
    | '/report'
    | '/settings'
    | '/skin-sense'
    | '/temp-sense'
    | '/onboarding/avatar'
    | '/onboarding/details'
    | '/onboarding/dog'
    | '/onboarding/owner'
    | '/onboarding/owner-info'
    | '/onboarding/welcome'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/avatar-setup'
    | '/bark-sense'
    | '/breeds'
    | '/clinics'
    | '/community'
    | '/home'
    | '/language'
    | '/light-sense'
    | '/map'
    | '/motion-sense'
    | '/pressure-sense'
    | '/report'
    | '/settings'
    | '/skin-sense'
    | '/temp-sense'
    | '/onboarding/avatar'
    | '/onboarding/details'
    | '/onboarding/dog'
    | '/onboarding/owner'
    | '/onboarding/owner-info'
    | '/onboarding/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  AvatarSetupRoute: typeof AvatarSetupRoute
  BarkSenseRoute: typeof BarkSenseRoute
  BreedsRoute: typeof BreedsRoute
  ClinicsRoute: typeof ClinicsRoute
  CommunityRoute: typeof CommunityRoute
  HomeRoute: typeof HomeRoute
  LanguageRoute: typeof LanguageRoute
  LightSenseRoute: typeof LightSenseRoute
  MapRoute: typeof MapRoute
  MotionSenseRoute: typeof MotionSenseRoute
  PressureSenseRoute: typeof PressureSenseRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  SkinSenseRoute: typeof SkinSenseRoute
  TempSenseRoute: typeof TempSenseRoute
  OnboardingAvatarRoute: typeof OnboardingAvatarRoute
  OnboardingDetailsRoute: typeof OnboardingDetailsRoute
  OnboardingDogRoute: typeof OnboardingDogRoute
  OnboardingOwnerRoute: typeof OnboardingOwnerRoute
  OnboardingOwnerInfoRoute: typeof OnboardingOwnerInfoRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temp-sense': {
      id: '/temp-sense'
      path: '/temp-sense'
      fullPath: '/temp-sense'
      preLoaderRoute: typeof TempSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-sense': {
      id: '/skin-sense'
      path: '/skin-sense'
      fullPath: '/skin-sense'
      preLoaderRoute: typeof SkinSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure-sense': {
      id: '/pressure-sense'
      path: '/pressure-sense'
      fullPath: '/pressure-sense'
      preLoaderRoute: typeof PressureSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-sense': {
      id: '/motion-sense'
      path: '/motion-sense'
      fullPath: '/motion-sense'
      preLoaderRoute: typeof MotionSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/light-sense': {
      id: '/light-sense'
      path: '/light-sense'
      fullPath: '/light-sense'
      preLoaderRoute: typeof LightSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeds': {
      id: '/breeds'
      path: '/breeds'
      fullPath: '/breeds'
      preLoaderRoute: typeof BreedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bark-sense': {
      id: '/bark-sense'
      path: '/bark-sense'
      fullPath: '/bark-sense'
      preLoaderRoute: typeof BarkSenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar-setup': {
      id: '/avatar-setup'
      path: '/avatar-setup'
      fullPath: '/avatar-setup'
      preLoaderRoute: typeof AvatarSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/owner-info': {
      id: '/onboarding/owner-info'
      path: '/onboarding/owner-info'
      fullPath: '/onboarding/owner-info'
      preLoaderRoute: typeof OnboardingOwnerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/owner': {
      id: '/onboarding/owner'
      path: '/onboarding/owner'
      fullPath: '/onboarding/owner'
      preLoaderRoute: typeof OnboardingOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dog': {
      id: '/onboarding/dog'
      path: '/onboarding/dog'
      fullPath: '/onboarding/dog'
      preLoaderRoute: typeof OnboardingDogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/details': {
      id: '/onboarding/details'
      path: '/onboarding/details'
      fullPath: '/onboarding/details'
      preLoaderRoute: typeof OnboardingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/avatar': {
      id: '/onboarding/avatar'
      path: '/onboarding/avatar'
      fullPath: '/onboarding/avatar'
      preLoaderRoute: typeof OnboardingAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  AvatarSetupRoute: AvatarSetupRoute,
  BarkSenseRoute: BarkSenseRoute,
  BreedsRoute: BreedsRoute,
  ClinicsRoute: ClinicsRoute,
  CommunityRoute: CommunityRoute,
  HomeRoute: HomeRoute,
  LanguageRoute: LanguageRoute,
  LightSenseRoute: LightSenseRoute,
  MapRoute: MapRoute,
  MotionSenseRoute: MotionSenseRoute,
  PressureSenseRoute: PressureSenseRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  SkinSenseRoute: SkinSenseRoute,
  TempSenseRoute: TempSenseRoute,
  OnboardingAvatarRoute: OnboardingAvatarRoute,
  OnboardingDetailsRoute: OnboardingDetailsRoute,
  OnboardingDogRoute: OnboardingDogRoute,
  OnboardingOwnerRoute: OnboardingOwnerRoute,
  OnboardingOwnerInfoRoute: OnboardingOwnerInfoRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
